@startuml

create "id1: Cardenal"
":TestCase" -> "id1: Cardenal": Cardenal("id1")
create "id6: Cardenal"
":TestCase" -> "id6: Cardenal": Cardenal("id6")
":TestCase" -> "id1: Cardenal": votar(id6)
":TestCase" -> "id2: Cardenal": votar(id6)
":TestCase" -> "id3: Cardenal": votar(id6)
":TestCase" -> "id4: Cardenal": votar(id6)
":TestCase" -> "id5: Cardenal": votar(id4)
":TestCase" -> "id6: Cardenal": votar(id1)
create "i: Impersonalizador"
":TestCase" -> "i: Impersonalizador": Impersonalizador()
create ":Conclave"
":TestCase" -> ":Conclave": Conclave(i, id1..id6)
loop "Para cada regla"
    ":Conclave" -> ":Regla": verificar()
end loop

":Conclave" --> ":TestCase": new HumoBlanco()


@enduml
